FileStorage/FileStorage/Controllers/AvailableDocumentsController.cs
namespace FileStorage.Controllers
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;
    using DAL.Interfaces;
    using DAL.Models;
    using Models;

    [Authorize]
    public class AvailableDocumentsController : Controller
    {
        private const int PageSize = 12;
        private IFileRepository fileRepository;
        private IUserRepository userRepository;
        private ITagRepository tagRepository;
        private IAccessRepository accessRepository;

        public AvailableDocumentsController(
            IFileRepository fileRepositoryParam,
            IUserRepository userRepositoryParam,
            ITagRepository tagRepositoryParam,
            IAccessRepository accessRepositoryParam)
        {
            fileRepository = fileRepositoryParam;
            userRepository = userRepositoryParam;
            tagRepository = tagRepositoryParam;
            accessRepository = accessRepositoryParam;
        }

        public ActionResult GetAvailableDocuments(int page = 1)
        {
            var model = new DocumentsViewModel();
            model.Documents = fileRepository.SearchAvailableDocuments(null, string.Empty, GetUserId())
                .OrderBy(d => d.DocumentID)
                .Skip((page - 1) * PageSize)
                .Take(PageSize);
            model.Tags = tagRepository.GetTags() as List<Tag>;
            model.PageInfo = new PageInfo
            {
                PageNumber = page,
                PageSize = PageSize,
                TotalItems = fileRepository
                    .SearchAvailableDocuments(null, string.Empty, GetUserId()).Count()
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult GetAvailableDocuments(DocumentsViewModel model, int page = 1)
        {
            var tags = new List<Tag>();

            if (model.Filter != null)
            {
                foreach (var tagName in model.Filter)
                {
                    tags.Add(new Tag());
                    tags.Last().TagID = tagRepository.GetTagID(tagName);
                }
            }

            var userId = GetUserId();

            model.Documents = fileRepository.SearchAvailableDocuments(tags, model.Title, userId)
                .OrderBy(d => d.DocumentID)
                .Skip((page - 1) * PageSize)
                .Take(PageSize);

            model.PageInfo = new PageInfo
            {
                PageNumber = page,
                PageSize = PageSize,
                TotalItems = fileRepository.SearchAvailableDocuments(tags, model.Title, userId).Count()
            };
            model.Tags = tagRepository.GetTags() as List<Tag>;

            return View(model);
        }

        public ActionResult Details(int id)
        {
            Document d = fileRepository.GetDocument(id);
            if (d != null)
            {
                return PartialView(d);
            }
            else
            {
                return HttpNotFound();
            }
        }

        public FileResult GetFile(string hash)
        {
            var document = fileRepository.GetDocument(hash);

            return File(document.Doc, document.Tag.Type, document.Title + document.Tag.TagName);
        }

        private int GetUserId()
        {
            return userRepository.SearchUserByLogin(User.Identity.Name).UserID;
        }
    }
}

FileStorage/FileStorage/Controllers/StorageController.cs
namespace FileStorage.Controllers
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;
    using DAL.Interfaces;
    using DAL.Models;
    using Models;

    public class StorageController : Controller
    {
        private const int PageSize = 12;
        private IFileRepository fileRepository;
        private IUserRepository userRepository;
        private ITagRepository tagRepository;
        private IAccessRepository accessRepository;

        public StorageController(
            IFileRepository fileRepositoryParam, 
            IUserRepository userRepositoryParam,
             ITagRepository tagRepositoryParam,
            IAccessRepository accessRepositoryParam)
        {
            fileRepository = fileRepositoryParam;
            userRepository = userRepositoryParam;
            tagRepository = tagRepositoryParam;
            accessRepository = accessRepositoryParam;
        }

        public ActionResult GetPublicDocuments(int page = 1)
        {
            var model = new DocumentsViewModel();
            model.Documents = fileRepository.SearchPublicDocuments(null, string.Empty)
                .OrderBy(d => d.DocumentID)
                .Skip((page - 1) * PageSize)
                .Take(PageSize);
            model.Tags = tagRepository.GetTags() as List<Tag>;
            model.PageInfo = new PageInfo
            {
                PageNumber = page,
                PageSize = PageSize,
                TotalItems = fileRepository.SearchPublicDocuments(null, string.Empty).Count()
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult GetPublicDocuments(DocumentsViewModel model, int page = 1)
        {
            var tags = new List<Tag>();

            if (model.Filter != null)
            {
                foreach (var tagName in model.Filter)
                {
                    tags.Add(new Tag());
                    tags.Last().TagID = tagRepository.GetTagID(tagName);
                }
            }

            model.Documents = fileRepository.SearchPublicDocuments(tags, model.Title)
                .OrderBy(d => d.DocumentID)
                .Skip((page - 1) * PageSize)
                .Take(PageSize);

            model.PageInfo = new PageInfo
            {
                PageNumber = page,
                PageSize = PageSize,
                TotalItems = fileRepository.SearchPublicDocuments(tags, model.Title).Count()
            };
            model.Tags = tagRepository.GetTags() as List<Tag>;

            return View(model);
        }

        public ActionResult Details(int id)
        {
            Document d = fileRepository.GetDocument(id);
            if (d != null)
            {
                return PartialView(d);
            }
            else
            {
                return HttpNotFound();
            }
        }

        public FileResult GetFile(string hash = null)
        {
            var document = fileRepository.GetDocument(hash);
            if (hash == null)
            {
                return null;
            }
            
            return File(document.Doc, document.Tag.Type, document.Title + document.Tag.TagName);
        }
    }
}

FileStorage/FileStorage/Controllers/UserDocumentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FileStorage.Controllers
{
    public class UserDocumentsController : Controller
    {
        // GET: Document
        public ActionResult Index()
        {
            return View();
        }
    }
}

FileStorage/FileStorage/Views/Shared/ErrorDefault.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="width=device-width" />
    <title>Ошибка</title>
</head>
<body>
    <hgroup>
        <h1>Ошибка.</h1>
        <h2>При обработке запроса произошла ошибка.</h2>
    </hgroup>
</body>
</html>

FileStorage/FileStorage/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("FileStorage", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Хранилище", "GetPublicDocuments", "Storage")</li>
                    @if (User.IsInRole("Admin"))
                    {
                        <li>@Html.ActionLink("Управление", "GetAllDocuments", "Admin")</li>
                    }
                    @if (!User.Identity.IsAuthenticated)
                    {
                        <li class="pull-right">@Html.ActionLink("Вход", "LogIn", "Account", "", new { @class = "" })</li>
                        <li class="pull-right">@Html.ActionLink("Регистрация", "Registration", "Account", "", new { @class = "" })</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Мои документы", "GetUserDocuments", "UserDocuments")</li>
                        <li>@Html.ActionLink("Доступные документы", "GetAvailableDocuments", "AvailableDocuments")</li>
                        <li class="pull-right">@Html.ActionLink("Выход", "LogOut", "Account")</li> 
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – приложение ASP.NET</p>
        </footer>
    </div>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>